architecture: standalone

fullnameOverride: "dke-mongodb"

auth:
  existingSecret: mongodb-db-creds
  usernames:
    - auditadmin
  databases:
    - auditdbadmin

persistence:
  size: 8Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      prometheus: default